//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegixInbound.DAL.B
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbFormFillEntities : DbContext
    {
        public dbFormFillEntities()
            : base("name=dbFormFillEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAutoFillForms> tblAutoFillForms { get; set; }
        public virtual DbSet<tblFieldsDocToRegixFields> tblFieldsDocToRegixFields { get; set; }
        public virtual DbSet<tblRegixSpravkaInfo> tblRegixSpravkaInfo { get; set; }
        public virtual DbSet<pdfGenerationInfoView> pdfGenerationInfoView { get; set; }
    }
}
