//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegixInbound.DAL.B
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAutoFillForms
    {
        public int IdAutoFill { get; set; }
        public string SessionId { get; set; }
        public string PersonId { get; set; }
        public string FormId { get; set; }
        public Nullable<System.DateTime> DateReg { get; set; }
        public string FilledFormPath { get; set; }
        public Nullable<System.DateTime> DateFormFill { get; set; }
        public Nullable<System.DateTime> SendetToPerson { get; set; }
        public byte[] FormData { get; set; }
    }
}
