//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegixInbound.DAL.B
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFieldsDocToRegixFields
    {
        public int IdAutoFill { get; set; }
        public string FormId { get; set; }
        public string FieldId { get; set; }
        public string RegixPADId { get; set; }
        public string RegixSpravkaId { get; set; }
        public string RegixSpravkaFieldId { get; set; }
        public Nullable<System.DateTime> DateReg { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string RegixSpravkaFieldPrefix { get; set; }
    }
}
