//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegixInbound.DAL.B
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRegixSpravkaInfo
    {
        public int idRegixSpravkaInfo { get; set; }
        public string RegixSpravkaId { get; set; }
        public string RequestTemplate { get; set; }
        public string FormId { get; set; }
        public string Operation { get; set; }
    }
}
